spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data.db
    username:
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: "classpath:db/migration"
